apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: eihdnrp41-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: eihdnrp41-go 
  name: eihdnrp41-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: eihdnrp41-go 
